displayName: Traefik Real IP (CF)
type: middleware
import: github.com/FilipK-CZ/traefik-real-ip-fixed

summary: When traefik is deployed behind a load balancer, it should get the real IP from the X-Forwarded-For or Cf-Connecting-Ip (if from Cloudflare) header. 

testData:
  excludednets:
    - "1.1.1.1/24"
